POST http://localhost:5000/api/blogs
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjYxZTYwZDlmOWNmNGNiNWFlODU5ZGFhZCIsImlhdCI6MTY0MjU1OTU5Nn0.J9d1npFUcOiuINvFmimlwJkjkVvivUnn7wSfFLJMqUM

{
    "title": "testing new blog post second time",
    "author": "myself",
    "url": "wwww.google.com"  
}